### ISSUE TITLE
Running CRPTree with custom tree

### ISSUE THREAD

**Issue by luisevonderwiese** [jyzhang27/CRPTree#1]
Hi,
I wanted to try out CRPTree on my own data. 
I have given a tree and a binary alignment and I am interested in the Phylogenetic trait association of each column in the alignment. Here is my code an the files are attached.

```
library(CRPTree)
apply.crp.method <- function(tree.name) {
    data = read.table("46glossesfull.csv", header=TRUE, row.names=1, colClasses='character')
    taxa_names = row.names(data)
    datamat = as.matrix(data)
    tab <- apply(datamat, 2, function(x){table(factor(x, levels=c(0,1)))})
    indsToUse <- apply(tab, 2, function(x){x[1] > 1 && x[2] > 1})
    datamat <- datamat[,indsToUse]
    tree<-read.tree(file=tree.name)
    tree$tip.label[tree$tip.label == "Ptg-E"] = "PtgE"
    for (col in 1:ncol(datamat)) {
        trait<-datamat[, col]
        converted.trait <- c()
        for (value in trait) {
            if (value == "0"){
                converted.trait = append(converted.trait, 0)
            } else if (value == "1"){
                converted.trait = append(converted.trait, 1)
            } else {
                converted.trait = append(converted.trait, -1)
            }
        }
        cur.tree<-list(edge = tree$edge, tip.label = converted.trait, Nnode = tree$Nnode)
        cur.tree.cpr<-pcrp_tree(cur.tree, 2)
        mu_hat <- compute_mu_hat(cur.tree.cpr, 500)
        print(mu_hat)
    }
}
apply.crp.method("IE2011_Cognates_rel_ANNOT.txt")
```

However, I obtain the following error:

```
Error in tip_order_added[N - i + 1] <- tip_to_add : 
  replacement has length zero
Calls: apply.crp.method ... get_tree_sufficient_stats -> count_same_attachments
Execution halted
```
I would be very thankful if you could help me, what is wrong here.

Regards, Luise
[46glossesfull.csv](https://github.com/jyzhang27/CRPTree/files/10970074/46glossesfull.csv)
[IE2011_Cognates_rel_ANNOT.txt](https://github.com/jyzhang27/CRPTree/files/10970083/IE2011_Cognates_rel_ANNOT.txt)

**Comment by jyzhang27** [comment]
Hi Luise,

Thank you for your interest in our method and our package! I would advise you to convert your object `cur.tree` into a usable format using `process_tree`. If your vector `converted.trait` has two categories, then you can directly use the line `cur.tree <- process_tree(cur.tree)`. If not, then you should specify a matrix with two columns: column 1=`converted.trait`, column 2= vector of (-1, -2) values indicating binary assignment.

I hope this helps, if this does not work, we can figure out a solution on our end. 

Best,
Julie

**Comment by luisevonderwiese** [comment]
Hi Julie,
thank you very much for your quick answer!
I changed the code such that converted.trait contains only -1 and -2 and I added the line you proposed.
Unfortunately, I obtain another error:
```
Error in write.tree(tree) : object "phy" must contain trees
Calls: apply.crp.method ... <Anonymous> -> <Anonymous> -> gsub -> is.factor -> write.tree
Execution halted
```
Do you have any idea, how this happened?

Best, Luise

**Comment by jyzhang27** [comment]
Hi Luise,

After looking at your code further, I believe your trees are not of class `phylo` (from package `ape`) which is the structure of all trees. Documentation from that package should help. Specifically, you should specify branch lengths in your `cur.tree` definition, then use `class(cur.tree) <- 'phylo'`. Hopefully that will help. 

Best,
Julie

**Comment by luisevonderwiese** [comment]
Hi Julie,
thank you very much! Your hint helped regarding this error, but lead to another one:
```
Error in process_tree(cur.tree) : Ties exist in internal nodes
Calls: apply.crp.method -> process_tree
Execution halted
```
I am sorry that this issue turns out to be not so easy...
Thank you for your support!
Luise

**Comment by jyzhang27** [comment]
Hi Luise,

Our method require internal nodes to be ranked (ie no two internal nodes being the same length from the root). Branch lengths need to be set accordingly. 

Best,
Julie

**Comment by JuliaPalacios** [comment]
This may work:
library("ape")
update_time<-function(tree, coal_times){
  #coal_times<-cumsum(coalescent.intervals(tree)$interval.length)
  #tiplabels();nodelabels()
  ##sort before update to avoid problems
  #xx1<-sort(n.t,index.return=T)
  old.edge<-tree$edge
  n.sample <- tree$Nnode + 1
  t.tot <- max(ape::node.depth.edgelength(tree))
  n.t <- t.tot - ape::node.depth.edgelength(tree) ##gives the node length
  new.n.t<-n.t
  #order nodes according to length, then coalescent times are in reverse order
  xx1<-sort(new.n.t,index.return=T)
  index<-(2*n.sample-1):(n.sample+1)
  for (j in (n.sample+1):(2*n.sample-1)){
    old.edge[which(tree$edge[,1]==xx1$ix[j]),1]<-index[j-n.sample]
    old.edge[which(tree$edge[,2]==xx1$ix[j]),2]<-index[j-n.sample]
  }
  new.n.t[(n.sample+1):(2*n.sample-1)]<-rev(coal_times)
  #If we sort them, we can get the correspondence between leaves and coal. times
  xx<-sort(new.n.t,index.return=T)
  new.edge<-old.edge
  for (j in (n.sample+1):(2*n.sample-1)){
    new.edge[which(old.edge[,1]==xx$ix[j]),1]<-index[j-n.sample]
    new.edge[which(old.edge[,2]==xx$ix[j]),2]<-index[j-n.sample]
  }
  new.edge.length<-new.n.t[new.edge[,1]]-new.n.t[new.edge[,2]]
  new.tree<-tree
  new.tree$edge<-new.edge
  new.tree$edge.length<-new.edge.length
  #new.tree$tip.label<-rev(tree$tip.label)
  tree2<-write.tree(new.tree)
  new.tree2<-read.tree(text=tree2)
  trees <- c(tree, new.tree2) 
  trees <- .compressTipLabel(trees)
  t2 <- trees[[2]]
  return(t2)
}

inter_coal_times<-coalescent.intervals(yourtree)$interval.length
inter_coal_times[which(inter_coal_times<=0.001)]<-.1
coal_times<-cumsum(inter_coal_times)
yourtree2<-update_time(yourtree,coal_times)

**Comment by luisevonderwiese** [comment]
Thank you both for your support!
As the tree I am considering, is not rooted, this will introduce quite some guessing and uncertainties to the considered setup. Addtionally, the features I consider have some missing data points, what cannot be captured with your approach (as far as I am concerned)
This is why I decided to find another method to check trait association.
Anyways, I was wondering, whether you think about extending your approach to handle missing data or unrooted trees,

Thank you very much!
Luise
