### ISSUE TITLE
ERROR: dependency 'apTreeshape' is not available for package

### ISSUE THREAD

**Issue by SotoLF** [jyzhang27/CRPTree#2]
I wasn't able to install the CRPTree by using the `devtools::install_github("jyzhang27/CRPTree")`

Error printed:

ERROR: dependency 'apTreeshape' is not available for package 'CRPTree'
* removing 'D:/R-4.2.1/library/CRPTree'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Lufesu/AppData/Local/Temp/RtmpQ5IRxS/filea16985db559c9/CRPTree_0.0.0.9000.tar.gz’ had non-zero exit status
  
  
After googling, it looks like the dependent package 'apTreeshape' is not available in CRAN.

`Package ‘apTreeshape’ was removed from the CRAN repository.

Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/apTreeshape).

Archived on 2023-09-28 as issues were not corrected despite reminders.

A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2023/2023-09-28_check_results_apTreeshape.html).

Please use the canonical form https://cran.r-project.org/package=apTreeshape to link to this page.`

Reference: https://cran.r-project.org/web/packages/apTreeshape/index.html

Is there a way to update your code so it doesn't depend on this removed package?

**Comment by jyzhang27** [comment]
Hello, thank you for the update on "apTreeshape". We have updated our package and hope you can download it successfully now.
